#!/usr/bin/env bash
# Pushes the curated edit as docs/curate-<date> and opens the PR, or comments the
# proposal on an already-open curator PR (policy step 6). Args: date marker head.
set -euo pipefail
date_tag="$1"; marker="$2"; head="$3"

if git diff --quiet -- website/content/docs; then
  echo "No edit proposed; clean no-op." >> "$GITHUB_STEP_SUMMARY"
  exit 0
fi

branch="docs/curate-${date_tag}"
git config user.name 'birdbrain-doc-curator[bot]'
git config user.email 'doc-curator@users.noreply.github.com'

body_file=.curator/pr_body.md
{
  echo "Weekly reconciliation of \`website/content/docs\` against \`main\` ${marker:0:8}..${head:0:8}."
  echo
  echo "## Changes"
  jq -r '.changes[]? | "- **\(.page)** — \(.section): \(.summary) _(cites: \(.cites | join(", ")))_"' .curator/author.json
  echo
  echo "## Not attempted"
  jq -r '(.not_attempted // []) | if length == 0 then "- none" else .[] | "- \(.page): \(.reason)" end' .curator/author.json
  echo
  echo "## Reviewer"
  echo "Author \`$AUTHOR_MODEL\`; reviewer \`$REVIEWER_MODEL\` verdict: **$(jq -r .verdict .curator/verdict.json)**"
  jq -r '.reasons[]? | "- " + .' .curator/verdict.json
  echo
  echo "## Merged PRs in window"
  jq -r '.[] | "- #\(.number) \(.title)"' .curator/prs.json
  echo
  echo "Run: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
  echo
  echo "Pull request description generated by Claude Code"
} > "$body_file"

open_pr="$(cat .curator/open_pr.txt 2>/dev/null || true)"
if [ -n "$open_pr" ]; then
  {
    echo "A newer curation window (${marker:0:8}..${head:0:8}) produced this proposal while #${open_pr} is still open. Not opening a second curator PR; merge or close this one and the next run will pick the window up again."
    echo
    echo '```diff'
    git --no-pager diff -- website/content/docs | head -c 60000
    echo '```'
    echo
    cat "$body_file"
  } | gh pr comment "$open_pr" --body-file -
  echo "Commented proposal on open curator PR #${open_pr}." >> "$GITHUB_STEP_SUMMARY"
  exit 0
fi

git checkout -b "$branch"
git add -- website/content/docs/*.mdx
git commit -q -m "docs(site): weekly curation ${date_tag}"
git push -u origin "$branch"
url="$(gh pr create --base main --head "$branch" \
  --title "docs(site): weekly curation ${date_tag}" \
  --label agent-pr --label documentation \
  --body-file "$body_file")"
echo "Opened ${url}" >> "$GITHUB_STEP_SUMMARY"
