#!/usr/bin/env bash
#
# Provision the birdbrain agent pipeline's machine GitHub account (ADR-0012):
# create the account, add it as a collaborator, mint a repo-scoped fine-grained
# PAT, store it outside any checkout, and verify the identity end to end.
# Re-run to rotate the token. Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

REPO="thebristolsound/birdbrain"
CONF_DIR="$HOME/.config/birdbrain-agent"
ENV_FILE="$CONF_DIR/env"        # never a repo .env — the token must not live in a checkout

TOTAL_STAGES=6
TOTAL_MINUTES=20

banner "birdbrain — agent machine account (ADR-0012)"

# ── 1. Preflight ──────────────────────────────────────────────────────────
stage "Preflight" 2
say "This wizard needs the maintainer's gh login (it invites the collaborator) and a"
say "private/incognito browser window for the machine account, so the two logins"
say "never mix. Nothing here touches your own gh auth."
command -v gh >/dev/null 2>&1 || { warn "gh is not installed — install it and re-run."; exit 1; }
MAINTAINER="$(gh api user --jq .login 2>/dev/null || true)"
[[ -n "$MAINTAINER" ]] || { warn "gh is not logged in — run 'gh auth login' as the maintainer and re-run."; exit 1; }
say "Maintainer login: ${BOLD}${MAINTAINER}${RESET}"
mkdir -p "$CONF_DIR" && chmod 700 "$CONF_DIR"
note "Token file will be $ENV_FILE (dir 0700, file 0600)."
if [[ -f "$ENV_FILE" ]]; then
  note "An existing file was found — Enter at any prompt keeps the stored value (rotation mode)."
fi
ask BIRDBRAIN_AGENT_GH_LOGIN "Machine account login to use (e.g. birdbrain-agent):"
[[ -n "$BIRDBRAIN_AGENT_GH_LOGIN" ]] || { warn "a login is required"; exit 1; }
[[ "$BIRDBRAIN_AGENT_GH_LOGIN" != "$MAINTAINER" ]] || { warn "that is your own login — the point is a *separate* account"; exit 1; }
write_env BIRDBRAIN_AGENT_GH_LOGIN "$BIRDBRAIN_AGENT_GH_LOGIN"
chmod 600 "$ENV_FILE"

# ── 2. Create the account ─────────────────────────────────────────────────
stage "Create the machine account" 6
if gh api "users/$BIRDBRAIN_AGENT_GH_LOGIN" >/dev/null 2>&1; then
  say "GitHub already has a user named ${BOLD}${BIRDBRAIN_AGENT_GH_LOGIN}${RESET}."
  if confirm "Is that your machine account (skip creation)?"; then
    note "skipping creation"
  else
    warn "Pick a different login — Ctrl-C and re-run."; exit 1
  fi
else
  say "Open a ${BOLD}private/incognito window${RESET} first — you are logged in as $MAINTAINER in the normal one."
  open_url "https://github.com/signup"
  step "Sign up with a distinct email. A plus-address on your own mailbox works"
  step "  (e.g. you+${BIRDBRAIN_AGENT_GH_LOGIN}@…) and keeps recovery in your hands."
  step "Username: ${BOLD}${BIRDBRAIN_AGENT_GH_LOGIN}${RESET}. Free plan is fine."
  note "GitHub's terms allow one machine-user account per person; this is that one."
  pause "Press Enter once the account exists and its email is verified."
  step "Still in the incognito window, enable two-factor auth (GitHub requires it for contributors):"
  open_url "https://github.com/settings/security"
  step "  Two-factor authentication → Enable → authenticator app. Save the recovery codes"
  step "  wherever you keep your own — this account can approve nothing, but losing it"
  step "  means rotating the token from scratch."
  pause "Press Enter once 2FA is on."
fi

# ── 3. Add as collaborator ────────────────────────────────────────────────
stage "Add as collaborator on $REPO" 3
say "The invite is sent from your ($MAINTAINER) login with ${BOLD}write${RESET} (push) permission."
say "Write is the collaborator level that can open PRs and set labels; the token minted"
say "next narrows what the pipeline can actually do."
if gh api "repos/$REPO/collaborators/$BIRDBRAIN_AGENT_GH_LOGIN" >/dev/null 2>&1; then
  note "$BIRDBRAIN_AGENT_GH_LOGIN is already a collaborator — nothing to send."
else
  if confirm "Send the collaborator invitation now?"; then
    gh api -X PUT "repos/$REPO/collaborators/$BIRDBRAIN_AGENT_GH_LOGIN" -f permission=push >/dev/null
    printf '  %s✓ invited%s %s\n' "$GREEN" "$RESET" "$BIRDBRAIN_AGENT_GH_LOGIN"
  else
    SKIPPED+=("collaborator invite for $BIRDBRAIN_AGENT_GH_LOGIN (gh api -X PUT repos/$REPO/collaborators/$BIRDBRAIN_AGENT_GH_LOGIN -f permission=push)")
    warn "skipped — the token stage will not work until the account has access"
  fi
  step "In the incognito window (machine account), accept the invitation:"
  open_url "https://github.com/$REPO/invitations"
  pause "Press Enter once accepted."
  until gh api "repos/$REPO/collaborators/$BIRDBRAIN_AGENT_GH_LOGIN" >/dev/null 2>&1; do
    warn "GitHub does not list $BIRDBRAIN_AGENT_GH_LOGIN as a collaborator yet."
    confirm "Accepted now — check again?" || { SKIPPED+=("collaborator acceptance not confirmed"); break; }
  done
fi

# ── 4. Mint the token ─────────────────────────────────────────────────────
stage "Mint the fine-grained token" 5
say "Still in the incognito window, as ${BOLD}${BIRDBRAIN_AGENT_GH_LOGIN}${RESET}:"
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: ${BOLD}birdbrain-dispatch${RESET}"
step "Expiration: pick one and note the date — you will enter it below."
step "Resource owner: ${BOLD}${BIRDBRAIN_AGENT_GH_LOGIN}${RESET} (the machine account itself)"
step "Repository access: ${BOLD}Only select repositories${RESET} → ${BOLD}$REPO${RESET}"
step "Repository permissions — set exactly these, leave the rest at No access:"
step "    Contents ........... Read-only      (needed to open PRs; cannot push)"
step "    Issues ............. Read and write (claim comments, labels, give-up relabels)"
step "    Pull requests ...... Read and write (open the draft PR, labels, review replies)"
step "    Commit statuses .... Read and write (the agent/pre-pass status)"
step "    Checks ............. Read-only      (gh pr checks — wait for CI before the pre-pass)"
step "    Metadata ........... Read-only      (set automatically)"
step "Account permissions: none."
step "Generate token, then copy it — it is shown once."
ask_secret BIRDBRAIN_AGENT_GH_TOKEN "Paste the token:"
[[ -n "$BIRDBRAIN_AGENT_GH_TOKEN" ]] || { warn "no token entered"; exit 1; }
ask BIRDBRAIN_AGENT_GH_TOKEN_EXPIRES "Expiry date you chose (YYYY-MM-DD):"
write_env BIRDBRAIN_AGENT_GH_TOKEN "$BIRDBRAIN_AGENT_GH_TOKEN"
write_env BIRDBRAIN_AGENT_GH_TOKEN_EXPIRES "$BIRDBRAIN_AGENT_GH_TOKEN_EXPIRES"
chmod 600 "$ENV_FILE"
note "Not written anywhere else: no repo .env, no Actions secret. Rotation = re-run this wizard."

# ── 5. Verify ─────────────────────────────────────────────────────────────
stage "Verify the identity end to end" 2
say "Running exactly the check the dispatch skill runs at the top of every cycle."
agh() { GH_TOKEN="$BIRDBRAIN_AGENT_GH_TOKEN" gh "$@"; }
SEEN="$(agh api user --jq .login 2>/dev/null || true)"
if [[ "$SEEN" == "$BIRDBRAIN_AGENT_GH_LOGIN" ]]; then
  printf '  %s✓%s token authenticates as %s\n' "$GREEN" "$RESET" "$SEEN"
else
  warn "token authenticates as '${SEEN:-<nothing>}', expected $BIRDBRAIN_AGENT_GH_LOGIN — re-mint in the right account"
  SKIPPED+=("token identity check failed (got '${SEEN:-<nothing>}')")
fi
PUSH="$(agh api "repos/$REPO" --jq .permissions.push 2>/dev/null || echo false)"
if [[ "$PUSH" == "true" ]]; then
  printf '  %s✓%s machine account has write access to %s\n' "$GREEN" "$RESET" "$REPO"
else
  warn "no write access to $REPO from this token — check the collaborator invite and the token's repository selection"
  SKIPPED+=("write access to $REPO not confirmed")
fi
ISSUES="$(agh api "repos/$REPO/issues?per_page=1" --jq length 2>/dev/null || echo err)"
[[ "$ISSUES" != "err" ]] && printf '  %s✓%s can read issues\n' "$GREEN" "$RESET" || warn "cannot read issues — Issues permission missing?"
note "Write permissions (issues, PRs, statuses) are only provable by writing; the first"
note "dispatch cycle is that test, and it stops before claiming the slot if any is missing."

# ── 6. Hand-off ───────────────────────────────────────────────────────────
stage "What changes from here" 2
say "• The dispatch skill sources $ENV_FILE and writes as $BIRDBRAIN_AGENT_GH_LOGIN."
say "• Do NOT 'gh auth login' as the machine account on this machine — the token is scoped"
say "  per call so your own login stays $MAINTAINER for everything else."
say "• You can now approve / request changes on agent PRs. Requiring that in the ruleset"
say "  is a separate, deliberate step."
say "• Log out of the incognito window; the account needs no further browser use until rotation."
pause

finish
