#!/usr/bin/env node
// Lints a PR body against ../template.md. Usage: lint-body.mjs [--any-author] <file>
// The file is Markdown, or JSON with a `body` string (a `gh api --input` payload).
// --any-author accepts a body without the attribution line (a human-written PR); the merge
// path uses it. The line, when present, must still be last.
// Prints one finding per line and exits 1 on any finding.
import { readFileSync } from 'node:fs'

const MAX_LINES_ABOVE_VERIFICATION = 40
const MAX_SUMMARY_SENTENCES = 5
const ATTRIBUTION = 'Pull request description generated by Claude Code'
const SECTIONS = ['## Summary', '## Changes', '## Evidence-affecting', '## Verification']
const IMPACT_FIELDS = [
  'Evidentiary result',
  'What verification proves',
  'Backward verification',
  'Known-answer test'
]
const PREFLIGHT_MARKER = /^<!-- preflight v\d+ sha=[0-9a-f]{40} status=\w+ -->$/
// The footer a cloud-proxy session appends after the body it was given (ADR-0022).
const PLATFORM_FOOTER = /^_?Generated (with|by) \[Claude Code\]\([^)]*\)_?$/
const FORBIDDEN = [
  [/co-authored-by/i, 'a Co-authored-by trailer'],
  [/Generated (with|by) \[Claude Code\]/, 'the platform attribution footer (the attribution line is the only one you author)'],
  [/Summary by CodeRabbit/, 'a CodeRabbit summary (CodeRabbit writes its own; never paste one)']
]

// Template prompts are HTML comments and do not count; the preflight marker is one too and does.
function stripComments(text) {
  return text.replace(/<!--[\s\S]*?-->/g, (m) =>
    /^<!-- preflight /.test(m) ? m : m.split('\n').map(() => '').join('\n')
  )
}

// A platform footer directly after the attribution line was appended by the platform, not
// authored; drop it so the rest of the body is judged as written.
function dropPlatformFooter(text) {
  const lines = text.split('\n')
  let i = lines.length - 1
  while (i >= 0 && lines[i].trim() === '') i--
  if (i < 1 || !PLATFORM_FOOTER.test(lines[i].trim())) return text
  let j = i - 1
  while (j >= 0 && lines[j].trim() === '') j--
  if (j < 0 || lines[j].trim() !== ATTRIBUTION) return text
  return lines.slice(0, j + 1).join('\n') + '\n'
}

function countSentences(text) {
  const prose = text
    .replace(/`[^`]*`/g, '')
    .replace(/\d+\.\d+/g, '')
    .replace(/\b(e\.g|i\.e|vs|etc)\./gi, '')
  return (prose.match(/[.!?](?=\s|$)/g) || []).length
}

export function lintBody(raw, { anyAuthor = false } = {}) {
  const findings = []
  const text = dropPlatformFooter(raw.replace(/\r\n/g, '\n'))
  const lines = text.split('\n')
  const visible = stripComments(text).split('\n')
  // A line that stripping emptied was a template prompt; it is not authored text.
  const fromComment = lines.map((l, i) => l.trim() !== '' && visible[i].trim() === '')

  for (const [re, what] of FORBIDDEN) {
    if (re.test(text)) findings.push(`body contains ${what}`)
  }

  const first = (visible.find((l) => l.trim() !== '') || '').trim()
  if (!/^Closes #\d+(, #\d+)*$/.test(first) && !/^No issue: \S.*$/.test(first)) {
    findings.push(`line 1 must be "Closes #N" (or "No issue: <reason>"), got: "${first.slice(0, 60)}"`)
  }

  const headings = []
  visible.forEach((l, i) => {
    if (/^#{1,6} /.test(l)) headings.push({ line: i, text: l.trim() })
  })
  const h2 = headings.filter((h) => h.text.startsWith('## ')).map((h) => h.text)
  if (h2.join('|') !== SECTIONS.join('|')) {
    findings.push(`sections must be exactly ${SECTIONS.join(', ')} in that order; got: ${h2.join(', ') || '(none)'}`)
  }
  for (const h of headings) {
    if (h.text.startsWith('# ')) findings.push(`no top-level heading: "${h.text}"`)
    if (h.text.startsWith('### ') && h.text !== '### Evidence impact') {
      findings.push(`no subsections except "### Evidence impact": "${h.text}"`)
    }
    if (/^#{4,} /.test(h.text)) findings.push(`no deep headings: "${h.text}"`)
  }

  const start = (name) => visible.findIndex((l) => l.trim() === name)
  const section = (name, next) => {
    const s = start(name)
    if (s < 0) return null
    let e = next ? start(next) : visible.length
    if (e < 0 || e < s) e = visible.length
    return { start: s, end: e, lines: visible.slice(s + 1, e) }
  }

  const summary = section('## Summary', '## Changes')
  if (summary) {
    const n = countSentences(summary.lines.join(' '))
    if (n > MAX_SUMMARY_SENTENCES) findings.push(`Summary has ${n} sentences; the cap is ${MAX_SUMMARY_SENTENCES}`)
    if (n === 0) findings.push('Summary is empty')
  }

  const changes = section('## Changes', '## Evidence-affecting')
  if (changes) {
    const bad = changes.lines.filter((l) => l.trim() !== '' && !/^\s*- /.test(l))
    if (bad.length) findings.push(`Changes holds only bullets; found prose: "${bad[0].trim().slice(0, 60)}"`)
    if (!changes.lines.some((l) => /^\s*- \S/.test(l))) findings.push('Changes has no bullets')
  }

  const evidence = section('## Evidence-affecting', '## Verification')
  if (evidence) {
    const answer = (evidence.lines.find((l) => l.trim() !== '') || '').trim()
    if (answer !== 'Yes' && answer !== 'No') {
      findings.push(`Evidence-affecting must answer "Yes" or "No" on its first line, got: "${answer.slice(0, 40)}"`)
    }
    const hasImpact = evidence.lines.some((l) => l.trim() === '### Evidence impact')
    if (answer === 'Yes') {
      if (!hasImpact) findings.push('Evidence-affecting is Yes but "### Evidence impact" is missing')
      const body = evidence.lines.join('\n')
      for (const f of IMPACT_FIELDS) {
        if (!body.includes(f)) findings.push(`Evidence impact is missing the "${f}" field`)
      }
    } else if (hasImpact) {
      findings.push('Evidence-affecting is No but carries an Evidence impact subsection')
    }
  }

  const vStart = start('## Verification')
  if (vStart >= 0) {
    const above = visible
      .slice(0, vStart)
      .filter((l, i) => !fromComment[i] && !PREFLIGHT_MARKER.test(l.trim()))
    if (above.length > MAX_LINES_ABOVE_VERIFICATION) {
      findings.push(`${above.length} lines above ## Verification; the cap is ${MAX_LINES_ABOVE_VERIFICATION}`)
    }
    if (above.some((l) => /^\s*```/.test(l))) {
      findings.push('fenced output above ## Verification; test output and figures live only in the Verification block')
    }
    const before = (visible[vStart - 1] || '').trim()
    const within = visible.slice(vStart + 1).some((l) => PREFLIGHT_MARKER.test(l.trim()))
    if (!PREFLIGHT_MARKER.test(before) && !within) {
      findings.push('Verification lacks the <!-- preflight v1 sha=... status=... --> marker; paste .preflight/verification.md verbatim')
    }
  }

  const last = ([...visible].reverse().find((l) => l.trim() !== '') || '').trim()
  const hasAttribution = visible.some((l) => l.trim() === ATTRIBUTION)
  if (hasAttribution && last !== ATTRIBUTION) {
    findings.push(`"${ATTRIBUTION}" must be the last line`)
  } else if (!hasAttribution && !anyAuthor) {
    findings.push(`the last line must be exactly "${ATTRIBUTION}"`)
  }

  return findings
}

function bodyFromFile(path) {
  const raw = readFileSync(path, 'utf8')
  if (path.endsWith('.json') || /^\s*\{/.test(raw)) {
    try {
      const j = JSON.parse(raw)
      if (typeof j.body === 'string') return j.body
    } catch {
      // not JSON after all; lint it as Markdown
    }
  }
  return raw
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  const args = process.argv.slice(2)
  const anyAuthor = args.includes('--any-author')
  const file = args.find((a) => !a.startsWith('--'))
  if (!file) {
    console.error('usage: lint-body.mjs [--any-author] <file>')
    process.exit(2)
  }
  const findings = lintBody(bodyFromFile(file), { anyAuthor })
  for (const f of findings) console.log(`- ${f}`)
  process.exit(findings.length ? 1 : 0)
}
